### ISSUE TITLE
GCP KCC processing files error for multiple yaml documents in the same file

### ISSUE THREAD

**Issue by farchide** [prancer-io/cloud-validation-framework#313]
In the Prancer Hello World, when we are running the KCC scenario it gives some errors

`prancer scenario-google-kcc`

```
 in "/var/folders/z0/508jxdg97n7cxg121c7nlwd00000gn/T/tmp81j_2y0e/samples/resources/monitoringalertpolicy/network-connectivity-alert-policy/monitoring_v1beta1_monitoringnotificationchannel.yaml", line 23, column 1
Failed to load yaml from file: /var/folders/z0/508jxdg97n7cxg121c7nlwd00000gn/T/tmp81j_2y0e/samples/resources/computevpntunnel/compute_v1beta1_computeforwardingrule.yaml, exception: expected a single document in the stream
```

It seems, prancer KCC processor expect one item in a each yaml file, but yaml files can contain multiple items which causes the problem:

```
apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryDataset
metadata:
  name: bigqueryjobdep1query
spec:
  friendlyName: bigqueryjob-dep1-query
  description: "Default Source BigQueryDataset"
---
apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryDataset
metadata:
  name: bigqueryjobdep2query
spec:
  friendlyName: bigqueryjob-dep2-query
  description: "Destination BigQueryDataset"
```
